controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    # use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    # camera_position_controller removed

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50  # Hz

mecanum_drive_controller:
  ros__parameters:
    reference_timeout: 0.5
    front_left_wheel_command_joint_name:  "base_front_left_wheel_joint"
    front_right_wheel_command_joint_name: "base_front_right_wheel_joint"
    rear_right_wheel_command_joint_name:  "base_rear_right_wheel_joint"
    rear_left_wheel_command_joint_name:   "base_rear_left_wheel_joint"
    front_left_wheel_state_joint_name:  "base_front_left_wheel_joint"
    front_right_wheel_state_joint_name: "base_front_right_wheel_joint"
    rear_right_wheel_state_joint_name:  "base_rear_right_wheel_joint"
    rear_left_wheel_state_joint_name:   "base_rear_left_wheel_joint"
    kinematics:
      wheels_radius: 0.0635
      sum_of_robot_center_projection_on_X_Y_axis: 0.525
      base_frame_offset:
        x: 0.0
        y: 0.0
        theta: 0.0
    tf_frame_prefix_enable: false
    tf_frame_prefix: ""
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: false
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    pose_covariance_diagonal:  [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

# camera controller configuration removed